### ISSUE TITLE
Naming of SSMRandomVariable in Graph

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#165]
If possible, we would want the actual model name to show up there. 

I tried something like this a longer while back and remember that it was a bit annoying, but if we can't get it to work, we should talk to the PyMC guys.

Can't imagine we are the only ones who would like to detach the name in the graphical model from the explicit RV class name.

**Comment by AlexanderFengler** [comment]
(There was supposed to be a picture of a model graph in there, but didn't show up...)

**Comment by digicosmos86** [comment]
I know what you are saying. I was also annoyed because they do have fields in `RandomVariable` that indicate variable names
