### ISSUE TITLE
Inconsistency in parameter naming in .graph()

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#168]
<img width="468" alt="Screen Shot 2023-07-06 at 4 38 21 PM" src="https://github.com/lnccbrown/HSSM/assets/5951150/2adfe3e1-c7e0-4a63-916d-3cc0ac5d5284">

(Assuming the pic uploaded)

If you add a regression to two parameters in the model:

One of them shows up as, `rt,response_paramname`, the other just as `paramname`.
Not sure what is causing this, but we should fix to drop the `rt,response_` part.

**Comment by digicosmos86** [comment]
Yeah this is a bambi issue. @tomicapretto and I have discussed this

**Comment by digicosmos86** [comment]
Seems that some aliases are not applied to non-parent parameters in distributional models

**Comment by AlexanderFengler** [comment]
He considers this fixable on bambi side, or suggestive of larger issue?

**Comment by tomicapretto** [comment]
@digicosmos86 do you have an example to reproduce this? I have a vague recollection of this issue, but I don't remember what was my guess at the time.

**Comment by digicosmos86** [comment]
> @digicosmos86 do you have an example to reproduce this? I have a vague recollection of this issue, but I don't remember what was my guess at the time.

Yeah @tomicapretto I shared with you one in Slack
