### ISSUE TITLE
Alignment of model_config entries

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#170]
<img width="703" alt="Screen Shot 2023-07-06 at 4 47 53 PM" src="https://github.com/lnccbrown/HSSM/assets/5951150/86fcefb7-c511-4dca-b8db-99844fd5ad68">

Contrast the two model config entries in the picture above. 
We should align this better so that it's more digestible / consistent / predictable for contributors / users. 

e.g. there should be 'backend' for both and there should be default priors for both, or at least if **only bounds** --> automatic assignment of uniform prior, then we should not specify `t` as Uniform[0,0.5] (anyways upper bounds was wrong, but I think that's fixed) but instead give only bounds to `t`.

**Comment by digicosmos86** [comment]
The analytical likelihood is a special case because we have to fix `initval`, so `default_priors` has to be used.

I think this issue will be clarified once we can use `inf` as bounds. We can also write a `hssm.show_defaults()` function to pretty print everything

**Comment by AlexanderFengler** [comment]
potentially separate prior key from initval key?

**Comment by digicosmos86** [comment]
We need more discussion on this. Tabbing this for `v0.1.2`
