### ISSUE TITLE
Need Brainstorm logo on landing and documentation pages

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#171]
currently brainstorm logo absent from everything

**Comment by digicosmos86** [comment]
This is kind of similar to #158

**Comment by digicosmos86** [comment]
Just to clarify, the `DOCS: footer` is for actually adding a footer to the documentation. the content of the footer can be more than just the Brainstorm logo. We have not really decided what to put into the header and footer, so currently it's unclear what is the best title for these issues
