### ISSUE TITLE
Add default model settings that turn every parameter hierarchical 

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#197]
If the data has a `subject` column, HSSM should have a `hierarchical` argument that sets every parameter to a basic regression model of the form `param ~ 1 + (1|subject)` with reasonable priors.

**Comment by digicosmos86** [comment]
@AlexanderFengler should we use something like `participant` or `participant_id` since the field has moved on from `subject`?

**Comment by digicosmos86** [comment]
@AlexanderFengler Also, what do you mean by "reasonable defaults"? I think Michael mentioned that we shouldn't be supplying defaults when a regression is specified. Should we just use bambi defaults?
