### ISSUE TITLE
priors not needed in model specification for regressions

### ISSUE THREAD

**Issue by frankmj** [lnccbrown/HSSM#212]
Ideally we should not need to add priors in the regression specification unless one wants those to deviate from default.  For hierarchical models where everything is hierarchical the model specification gets lengthy and removing priors would clean it up especially in which one needs to write formulas for each param. is it possible to just have the priors set to be default if not listed?

**Comment by digicosmos86** [comment]
Yes, it is possible. If priors for regressions are not specified, `bambi` will choose optimal defaults

**Comment by digicosmos86** [comment]
This is resolved through #223 :)
