### ISSUE TITLE
Better GPU support

### ISSUE THREAD

**Issue by digicosmos86** [lnccbrown/HSSM#237]
We can likely allow `pip install hssm[gpu]` to install optional GPU dependencies.

**Comment by AlexanderFengler** [comment]
yeah that's a good way of doing it actually. Mirrors `jax[gpu]` (if I remember correctly) :)

**Comment by digicosmos86** [comment]
@AlexanderFengler I am going to tab this as a nice-to-have for a future version. Right now there are a few blockers that prevent this from happening: 1. Poetry has poor support for optional dependencies with different extras, so we need to switch to either `hatch` or `pdm`. 2. Once we do this, numpyro gets weird about its dependencies, so we might either remove `jax` as a dependency and get it through numpyro or make numpyro as an optional dependency again. Both need some decision-making, so let's decide on this later
