### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by psychoxiatao** [lnccbrown/HSSM#243]
Hello~

An error occurs when I attempt to install HSSM directly using the command "pip install git+https://github.com/lnccbrown/HSSM.git".

Building wheel for ssm-simulators (pyproject.toml) ... error 
error: subprocess-exited-with-error

  × Building wheel for ssm-simulators (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\ssms
      copying ssms\__init__.py -> build\lib.win-amd64-cpython-39\ssms
      creating build\lib.win-amd64-cpython-39\ssms\basic_simulators
      copying ssms\basic_simulators\boundary_functions.py -> build\lib.win-amd64-cpython-39\ssms\basic_simulators
      copying ssms\basic_simulators\drift_functions.py -> build\lib.win-amd64-cpython-39\ssms\basic_simulators
      copying ssms\basic_simulators\simulator.py -> build\lib.win-amd64-cpython-39\ssms\basic_simulators
      copying ssms\basic_simulators\__init__.py -> build\lib.win-amd64-cpython-39\ssms\basic_simulators
      creating build\lib.win-amd64-cpython-39\ssms\config
      copying ssms\config\config.py -> build\lib.win-amd64-cpython-39\ssms\config
      copying ssms\config\__init__.py -> build\lib.win-amd64-cpython-39\ssms\config
      creating build\lib.win-amd64-cpython-39\ssms\dataset_generators
      copying ssms\dataset_generators\lan_mlp.py -> build\lib.win-amd64-cpython-39\ssms\dataset_generators
      copying ssms\dataset_generators\snpe.py -> build\lib.win-amd64-cpython-39\ssms\dataset_generators
      copying ssms\dataset_generators\__init__.py -> build\lib.win-amd64-cpython-39\ssms\dataset_generators
      creating build\lib.win-amd64-cpython-39\ssms\support_utils
      copying ssms\support_utils\kde_class.py -> build\lib.win-amd64-cpython-39\ssms\support_utils
      copying ssms\support_utils\__init__.py -> build\lib.win-amd64-cpython-39\ssms\support_utils
      running build_ext
      building 'cssm' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ssm-simulators
Successfully built hssm jax
Failed to build ssm-simulators
ERROR: Could not build wheels for ssm-simulators, which is required to install pyproject.toml-based projects

**Comment by digicosmos86** [comment]
Hello @psychoxiatao! This is because HSSM has the `ssm_simulators` dependency which is partly written in Cython. My guess is that you are on windows and Cython dependencies will have to be compiled. However, Windows does not usually come with C/C++ compilers, hence the error. You can follow [this link](https://visualstudio.microsoft.com/visual-cpp-build-tools/) to download and install Microsoft Build Tools. After it is installed, please run `pip install hssm` again, and you should be good to go :)

**Comment by digicosmos86** [comment]
Close as complete. Please feel free to reopen this issue if the problem is not resolved.
