### ISSUE TITLE
Internet connectivity required for approx_differentiable likelihoods?

### ISSUE THREAD

**Issue by jmasis** [lnccbrown/HSSM#248]
Hi there, I got the following error when trying to set up some models:

LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

I was able to pinpoint the problem to most likely be the log likelihood type. If I define the following model, I have no issues:

model = hssm.HSSM(
    data=data,
    model="ddm",
)

If I modify it, however to this, then I have a problem:

model = hssm.HSSM(
    data=data,
    model="ddm",
    loglik_kind="approx_differentiable"
)

I ran into this problem trying to define "angle" models.

The interactive nodes at Princeton don't have internet connectivity, so I'm just checking that that's what this issue is about. If so, is there a way to download the likelihoods locally as part of the package?

**Comment by digicosmos86** [comment]
Yes. We host our models as onnx files on our huggingface repo [here](https://huggingface.co/franklab/HSSM). The models are downloaded as needed to reduce the size of our package. You can download the model files from the repo and provide the path to the `onnx` file when you create the model with `hssm.HSSM` like this:

``` python
model = hssm.HSSM(
data=data,
model="ddm",
loglik_kind="approx_differentiable",
loglik="angle.onnx" # provide the path to the onnx file here
)
```

**Comment by digicosmos86** [comment]
Close as completed
