### ISSUE TITLE
HSSM Installation Error:  Could not build wheels for ssm-simulators, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by njhenein** [lnccbrown/HSSM#305]
I'm attempting to install the HSSM package through an Anaconda cmd prompt and I get an error each time stating that: "Failed to build ssm-simulators
ERROR: Could not build wheels for ssm-simulators, which is required to install pyproject.toml-based projects"

**HSSM version**
Not sure what version it is, I'm just doing pip install hssm

**To Reproduce**
pip install hssm 

**Screenshots**

**Additional context**
Add any other context about the problem here, such as the print out of the model.

**Comment by digicosmos86** [comment]
Hi,

Which operating system are you on? Most Windows systems do not come with default build tools to build some of the packages that we depend on.

Can you try our latest dev build `pip install git+https://github.com/lnccbrown/HSSM.git`? This should have pre-built wheels for all of our dependencies.

Please let me know if this works
Thanks!

**Comment by njhenein** [comment]
@digicosmos86 I'm on Windows 10. I tried the link and it seems to be working but there's an issue at the end with an "OSError: [WinError 5] access is denied." However, it's likely this error isn't related to the package itself.

**Comment by digicosmos86** [comment]
Yeah, it does seem like a permission issue. I am going to close this for now. Please feel free to reopen it if you experience further issues.
