### ISSUE TITLE
Main effect included in model with only interaction terms

### ISSUE THREAD

**Issue by hummuscience** [lnccbrown/HSSM#308]
**Describe the bug**
I am trying to model an interaction only (:) without the main effects. I expect that using the formula `v ~ 1 + conf:stim` would only estimate an `Intercept` and the interaction `conf:stim`. Instead, the model estimates `Intercept`, `stim`, and `conf:stim`.

Removing the intercept with `v ~ 0 + conf:stim` estimates only the interaction term `conf:stim`.

Since I expect Bambi/formulae/patsy to copy the common formula conventions from packages like lme4, I tested the formula there too, and got the expected results.

Is HSSM doing something in addition/different? Or is the syntax for Bambi different?

It seems like this is the way Bambi deals with the syntax, with is definitely different that what is standard in the field!

**HSSM version**
0.15

**To Reproduce**

``` python
model_side = hssm.HSSM(
    data=cav_data,
    model="ddm",
    t = 2,
    a = 2,
    z = 0.5,
    hierarchical = False,
    include=[
    {
        "name": "v",  # Drift rate
        "formula": "v ~ 1 + conf:stim",
        "link": "identity",
    }
    ],
)
```

```
Hierarchical Sequential Sampling Model
Model: ddm

Response variable: rt,response
Likelihood: analytical
Observations: 3988

Parameters:

v:
    Formula: v ~ 1 + conf:stim
    Priors:
        v_Intercept ~ Normal(mu: 0.0, sigma: nan)
        v_stim ~ Normal(mu: [0. 0.], sigma: [5.0003 5.791 ])
        v_conf:stim ~ Normal(mu: [0. 0. 0.], sigma: [   inf 5.0003    inf])
    Link: identity
    Explicit bounds: (-inf, inf)
a:
    Prior: 2.0
    Explicit bounds: (0.0, inf)
z:
    Prior: 0.5
    Explicit bounds: (0.0, 1.0)
t:
    Prior: 2.0
    Explicit bounds: (0.0, inf)

Lapse probability: 0.05
Lapse distribution: Uniform(lower: 0.0, upper: 10.0)
```

Here is for Bambi:

``` python
import bambi as bmb

# Read data
csv_url = 'https://raw.githubusercontent.com/haripen/Bambi_Analysis/main/sim_xover.csv'
df = pd.read_csv(csv_url,index_col=0,header=0)

bmb.Model('value ~ treatment:sequence', data = df)
```

```
       Formula: value ~ treatment:sequence
        Family: gaussian
          Link: mu = identity
  Observations: 240
        Priors: 
    target = mu
        Common-level effects
            Intercept ~ Normal(mu: 2.575700044631958, sigma: 88.95659637451172)
            sequence ~ Normal(mu: 0.0, sigma: 101.8489990234375)
            treatment:sequence ~ Normal(mu: [0. 0.], sigma: [124.739  108.8811])
        
        Auxiliary parameters
            sigma ~ HalfStudentT(nu: 4.0, sigma: 19.958200454711914)
```

**Comment by digicosmos86** [comment]
This does seem to be different from the R world. @tomicapretto any insights?

**Comment by tomicapretto** [comment]
> This does seem to be different from the R world. @tomicapretto any insights?

Have a look at this https://github.com/bambinos/bambi/issues/747#issuecomment-1785829611

And in particular, about the difference with R, the 7th bullet point here https://patsy.readthedocs.io/en/latest/R-comparison.html#r-comparison

**Comment by Cumol** [comment]
I had a feeling this was intentional. Even though I don't understand it completely, but it seems like ` y ~ a:b`  has the same flexibility as `y ~ a + b + a:b`. So if I am mainly interested in the interaction (a:b), I should just leave out the intercept and go with `y ~ 0 + a:b`.

Am I understanding this right?

**Comment by tomicapretto** [comment]
@Cumol correct! In all those cases your model uses the same information. What changes is the interpretation of the coefficients. When you do `~ 0 + a:b`, each coefficient is the mean of the group given by the combination of the levels in "a" and "b".

**Comment by digicosmos86** [comment]
Looks like this is resolved? Feel free to reopen if not
