### ISSUE TITLE
Add a bunch of bambi-usable, truncated distributions to the package

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#311]
We want distributions of the form,

```
def TruncatedNormal(name, mu, sigma, lower, upper, *args, dims=None, **kwargs):
    normal_dist = pm.Normal.dist(mu=mu, sigma=sigma)
    return pm.Truncated(name, normal_dist, lower=lower, upper=upper, *args, dims=dims, **kwargs)

def TruncatedWeibull(name, alpha, sigma, lower, upper, *args, dims=None, **kwargs):
    weibull_dist = pm.Weibull.dist(alpha=alpha, sigma=sigma)
    return pm.Truncated(name, weibull_dist, lower=lower, upper=upper, *args, dims=dims, **kwargs)

def TruncatedGamma(name, alpha, beta, lower, upper, *args, dims=None, **kwargs):
    gamma_dist = pm.Gamma.dist(alpha=alpha, beta=beta)
    return pm.Truncated(name, gamma_dist, lower=lower, upper=upper, *args, dims=dims, **kwargs)
```

included in the package directly, so that we can call them by name when constructing HSSM models.

**Comment by digicosmos86** [comment]
FYI, @AlexanderFengler check this out https://github.com/lnccbrown/HSSM/blob/99dc88abf9dd37a1583c5e8f96dae3e240575b90/src/hssm/prior.py#L24. This is basically a superset of the examples in this issue. Basically, this already allows for truncated distributions to be created with syntax like `{"name": "Normal", "mu": 0, "sigma": 1, "bounds": (-1, 1) }` or equivalently, `hssm.Prior("Normal", mu=0, sigma=1, bounds=(-1, 1)`. We probably don't need to change the code at all.

**Comment by AlexanderFengler** [comment]
Oh yeah I missed that in the Bambi code! @digicosmos86 
Is this wrapping pm.Truncated internally so if we pass a dist (not a string), it will wrap it?
If yes then I agree we can just skip this issue and relegate this to tutorials later.
