### ISSUE TITLE
Model Interpretation+ Errors in "mcmc" sampler.

### ISSUE THREAD

**Issue by tooweisiannn** [lnccbrown/HSSM#317]
Hello there, 

We are fitting a hssm drift diffusion model (ddm) to our experiment data. Our problem is with our model interpretability, as we do not understand what the model inference when sampling is producing. Specifically, what does the t[xxx] correspond to? Furthermore, whenever running the model, when we call model.sample, the compiler raises type conversion errors, and we can't seem to identify the source of it and/or if the errors will affect the output (since the program still runs to completion).

<img width="1107" alt="Screen Shot 2023-11-06 at 1 06 51 PM" src="https://github.com/lnccbrown/HSSM/assets/111456925/c02c6cf9-2023-4ac5-8bde-2a280d2b3e8a">

One shows many errors that we are getting during the model.sample.

<img width="1286" alt="Screen Shot 2023-11-06 at 1 07 15 PM" src="https://github.com/lnccbrown/HSSM/assets/111456925/f83331f3-0bde-4bbd-ad96-56fae4732894">

One shows the t[xxx] producing the same results over. Perhaps the model is not converging?

Thank you so much!

**Comment by AlexanderFengler** [comment]
Hi @tooweisiannn,

could you provide, in addition to the call of the `.sample()` method, also the actual model definition you are using?

Re. what the `t[xxx]` are.

These are the trial wise t-parameters you get out of the regression model. 
Bambi creates PyMC 'deterministics' under the hood to perform the computations related to the linear models. We are working on allowing to turn that off and on at will, but at the moment we are inheriting Bambi defaults in this regard.

Re. error code concerning the float32 / float64 matrices.

Potentially you are supplying float64 data while having pytensor.defaults set to float32?
(It is definitely something like that).

Anyways we will benefit from seeing the complete code here.
