### ISSUE TITLE
add argument to make everything hierarchical (like hddm did by default)

### ISSUE THREAD

**Issue by frankmj** [lnccbrown/HSSM#363]
hddm users will expect everything to be hierarchical and in principle this is better anyway, where one should only opt out of hierarchy for certain parameters if they want (eg. group_only_regressors = true for hddm).  This doesn't remove flexibility if one can set the argument off but it becomes very unwieldy to write down the full hierarchical model when there are several terms and interactions in a regression

**Comment by AlexanderFengler** [comment]
Still not perfectly sure how to do this in a satisfying way, closing for now.
