### ISSUE TITLE
Add functions from previous HDDM-Lan extension (cartoon-like plots)

### ISSUE THREAD

**Issue by gingjehli** [lnccbrown/HSSM#402]
It looks like some of the functions that had been added to HDDM as part of the previous LAN extension are not yet implemented in HSSM?
For instance, I very much appreciated the latest add-ons to HDDM that allowed me to draw cartoon-like graphics of different models. This concerns examples and functions outlined here: https://hddm.readthedocs.io/en/latest/tutorial_model_plot.html. 
For instance, the following functions don't seem applicable in HSSM:

hddm.plotting.plot_from_data()
hddm_preprocess(out,subj_id = '0',add_model_parameters = True)

Are there other methods in HSSM to draw these cartoon-like graphics?

**Comment by AlexanderFengler** [comment]
Hey Nadja, 

we are working to integrate the model cartoon plots back into HSSM. This is currently in an intermediate stage, might take a few more weeks to be part of an update. 

I had previously done a lot of work to make those plots play well with the HDDM codebase. I did the intermediate work of making them work independently again (this is sitting in some little dashboard app that we are trying to make available in a bit) however I still need to re-integrate with HSSM.

**Comment by digicosmos86** [comment]
We have this tabbed in #291. Closing for now
