### ISSUE TITLE
suspicious upper bounds on t

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#447]
I ran into situations where the `t` parameter was upper-bounded by the lowest `rt` in the data, even though `p_outlier > 0` was set. This shouldn't happen, and needs some investigation.

**Comment by digicosmos86** [comment]
It turns out that we replace the likelihood with a lower_bound whenever `rt < t` regardless of the value of `p_outlier`. This should be relaxed when `p_outlier > 0`. A fix is coming in the next few days

**Comment by AlexanderFengler** [comment]
@digicosmos86 this is actually resolved with your latest PR right?
