### ISSUE TITLE
Allow PyMC >= 5.15 

### ISSUE THREAD

**Issue by AlexanderFengler** [lnccbrown/HSSM#479]
Right now we are capping the PyMC dependency version at `<5.15`. Simply releasing the version constraint fails our tests, because some class signatures changed on the PyMC side. 

This is a placeholder issue for the internal work necessary to accommodate PyMC `>=5.15`.

**Comment by digicosmos86** [comment]
I'll work on this now. Graphing will still break, which will be fixed once bambi is updated
