### ISSUE TITLE
Cannot replicate graph in "One parameter is a Regression Target" in main tutorial

### ISSUE THREAD

**Issue by ThomasMurray14** [lnccbrown/HSSM#487]
Hi! Apologies if this has been posted several times, I've had some troubles raising issues with my github account. 

I've been following along with the main tutorial, and I can't reproduce the output in this section:
https://lnccbrown.github.io/HSSM/tutorials/main_tutorial/#case-1-one-parameter-is-a-regression-target

From the graph (in my code), it looks like the v parameter is not set by the regression coefficients, but rather those coefficients are treated the same as the other parameters:

<img width="431" alt="ddm" src="https://github.com/lnccbrown/HSSM/assets/41687196/dea885ff-0de1-4c43-9b42-1c9c60a4c6f0">

If I try to estimate the model anyway, the v distribution looks mental:

![bad_ddm](https://github.com/lnccbrown/HSSM/assets/41687196/3887c9a5-3c7a-47e7-9f53-d0029d7fe5da)

I've installed HSSM (0.2.1) in a conda environment, following the installation instructions. The only additional thing I've done is install spyder. I also installed pymc=5.10 (following the instructions), as the graph visualisation didn't work with the latest version

My code is the same as on the tutorial (except I've removed the theta parameter from the last column of the matrix, as the ddm model crashed when it was included):

```
# Set up trial by trial parameters. v is linear combination of x and y. Beta for x = 0.8, beta for y = 0.3. Intercept = 0.3
intercept = 0.3
x = np.random.uniform(-1, 1, size=1000)
y = np.random.uniform(-1, 1, size=1000)
v = intercept + (0.8 * x) + (0.3 * y)

true_values = np.column_stack(
    [v, np.repeat([[1.5, 0.5, 0.2]], axis=0, repeats=1000)]
)

# Get model simulations
obs_ddm_reg_v = simulator(true_values, model="ddm", n_samples=1)
dataset_reg_v = pd.DataFrame(
    {
        "rt": obs_ddm_reg_v["rts"].flatten(),
        "response": obs_ddm_reg_v["choices"].flatten(),
        "x": x,
        "y": y,
    }
)

model_reg_v = hssm.HSSM(
    model="ddm",
    data=dataset_reg_v,
    include=[
        {
            "name": "v",
            "formula": "v ~ 1 + x + y",
            "prior": {
                "Intercept": {"name": "Uniform", "lower": -3.0, "upper": 3.0},
                "x": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
                "y": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
            },
            "link": "identity",
        }
    ],
)

model_reg_v.graph()
```

**Comment by digicosmos86** [comment]
Hi @ThomasMurray14! Thank for reporting this issue! We are aware of this issue. Recent updates in PyMC and Bambi has introduced some breaking changes in their api and we are trying to update HSSM to accommodate these changes. Fixing graphing issues is our priority. Will let you know when this is fixed.
