### ISSUE TITLE
Decide if doing nothing before check?

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#500]
https://github.com/lnccbrown/HSSM/blob/2b8fadbd1098c54e449ba95dbec963eb7d5a4617/src/hssm/param.py#L101-L104

**Comment by digicosmos86** [comment]
Not sure about this. The idea of `_ensure_not_converted()` is to `freeze` the entire class, so no further changes can be made. So this check should always happen before any computation is made

**Comment by cpaniaguam** [comment]
I see what you mean but if the check in L103 passes no computations will be made. That's why I thought of maybe inverting the order here.

**Comment by digicosmos86** [comment]
Closing this. This is no longer issue after the Param refactor is introduced
