### ISSUE TITLE
Make override_default_priors_x docstrings dynamic with template

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#502]
- [ ] Docstrings dynamic?

https://github.com/lnccbrown/HSSM/blob/2b8fadbd1098c54e449ba95dbec963eb7d5a4617/src/hssm/param.py#L132-L133

- [ ] Almost the same logic. Unify in helper method with a `type` argument (`'general'` or `'default'` and `'ddm'`) to choose prior getter accordingly.

**Comment by digicosmos86** [comment]
Sounds good to me!
