### ISSUE TITLE
Use template for Param.__repr__

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#504]
https://github.com/lnccbrown/HSSM/blob/2b8fadbd1098c54e449ba95dbec963eb7d5a4617/src/hssm/param.py#L463-L480

**Comment by digicosmos86** [comment]
We can definitely use jinja

**Comment by cpaniaguam** [comment]
@digicosmos86 I was thinking something even simpler like
```python
MYTEMPLATE = """
{name}: 
    Value: {prior}
More things with fields....
"""
```
Then do `MYTEMPLATE.format(**kwargs)`:
```python
>>> MYTEMPLATE = """
... {name}:
...     Value: {prior}
... More things with fields...
... """
>>> fields = dict(name='My name', prior='My prior')
>>> print(MYTEMPLATE.format(**fields))

My name:
    Value: My prior
More things with fields...

**Comment by digicosmos86** [comment]
Sure! The HSSM class also uses something similar for its `__repr__`, and that one is a bit more complicated. Maybe we can just do something similar for both of them, as long as they are consistent?

**Comment by cpaniaguam** [comment]
Yeah, `HSSM.__repr__` can benefit from this kind of refactoring as well!
