### ISSUE TITLE
How to set initial values for parameters for individual factor levels in regression formula?

### ISSUE THREAD

**Issue by SaschaFroelich** [lnccbrown/HSSM#530]
Setting initial values can be important for good inference. I understand that I can set initial values like so for example:

```
model_reg_v_angle_hier = hssm.HSSM(
    data=ddmdata,
    model="angle",
    
    a = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=1.0),
    t = bmb.Prior("Uniform", lower=0., upper=2.0, initval=0.2),
    v = bmb.Prior("Uniform", lower=0., upper=2.0, initval=2.0),
    z = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=0.5),
    theta = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=1),
)
```

However, now I want to define the drift rate as a function of the task condition (`taskcondition`), which in my case is a categorical variable with three levels:

```
model_reg_v_angle_hier = hssm.HSSM(
    data=ddmdata,
    model="angle",
    
    a = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=1.0),
    t = bmb.Prior("Uniform", lower=0., upper=2.0, initval=0.2),
    z = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=0.5),
    theta = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=1),

    include=[
        {
            "name": "v",
            "prior": {
                "Intercept": {
                    "name": "Uniform",
                    "lower": -4.0,
                    "upper": 4.0,
                    "initval": 2.0,
                },
            },
            "formula": "v ~ (1|taskcondition) ",
            "link": "identity",
        }
    ],

)
```

I wonder how to set the group-level inital values for taskcondition? az.summary will contain the following varibales (among others):

`v_1|taskcondition[1.0]
v_1|taskcondition[2.0]
v_1|taskcondition[3.0]
v_1|taskcondition_sigma
v_Intercept`

First of all, as is evident from the [tutorial](https://lnccbrown.github.io/HSSM/tutorials/main_tutorial/#case-2-one-parameter-is-a-regression-lan), although the variable is called `v_Intercept` in the summary, its name in `include` should just be `Intercept`? So, is it correct to do something like this:

```
include=[
    {
        "name": "v",
        "prior": {
            "Intercept": {
                "name": "Uniform",
                "lower": -4.0,
                "upper": 4.0,
                "initval": 2.0,
            },
            "taskcondition[1.0]": {
                "name": "Uniform",
                "lower": -4.0,
                "upper": 4.0,
                "initval": 2.0,
            },
            "taskcondition[2.0]": {
                "name": "Uniform",
                "lower": -4.0,
                "upper": 4.0,
                "initval": 2.0,
            },
            "taskcondition[3.0]": {
                "name": "Uniform",
                "lower": -4.0,
                "upper": 4.0,
                "initval": 2.0,
            },
        },
        "formula": "v ~ (1|taskcondition) ",
        "link": "identity",
    }
],
```
?

What is more confusing, within the `prior` braces of `v`, I can include any kind of variable name without getting an error, so I don't really know whether my input is semantically correct or not. 

So is above the correct way to set the initial values for `taskcondition[1.0]` `taskcondition[2.0]` and `taskcondition[3.0]`?

Thank you,
Sascha

I'm using HSSM 0.2.1

**Comment by frankmj** [comment]
As I just wrote in #528 you don't want task condition to be modeled
hierarchically within-subject.

Instead you can do v ~ 1+ taskcondition  (and then add hierarchy
across subjects later if you want)

then the prior would be set like so:

(note I didn't use uniform priors here as I think you are usually better
using somewhat more informed ones, but you can change that to whatever you
want.) There is no hierarchy here but one can add that if you want to model
it hierarchically across subjects.  The key is that you can specify the
initials for the task condition as an array (here I just 0,0). note there
are two values for the initval because these are each going to be estimated
for two different task conditions relative to the intercept (which will
serve as the value for the third condition)

model_reg_v_angle_hier = hssm.HSSM(
    data=ddmdata,
    model="angle",

     include=[
        {
            "name": "v",
            "formula": "v ~ 1 + taskcondition",
            "prior": {
                "Intercept": {"name": "Normal", "mu": 1, "sigma": 2,
"initval": 1},
                "taskcondition: {"name": "Normal", "mu": 0, "sigma":
1, "initval": [0.0, 0.0]},
                             },

**Comment by frankmj** [comment]
note that for these initvals to actually take effect properly you have to
be using float64.
ie during your initial imports use
hssm.set_floatX("float64")

@Paul Xu ***@***.***> not sure if that is a bug just notices the
initial points don't take effect with float32.

**Comment by SaschaFroelich** [comment]
Thank you Michael.

So just to make sure, `v ~ 1+ (1|taskcondition)` would model the taskcondition hierarchically within subjects, while `v ~ 1+ taskcondition` does not? Is there a link with resources regarding this aspect that you could point me to? 

Best,
Sascha

**Comment by frankmj** [comment]
Hi Sascha, yes the | operator makes the estimation group wise (see
documentation for bambi or lme4 which both use this formula notation, e.g.
here
<https://bambinos.github.io/bambi/notebooks/multi-level_regression.html>).

In hssm you should see that in the model inference output, where it would
give you a v estimate for each task condition (e.g. v_1|taskcondition1,
v_1|taskcondition2) but also a mu and sigma for v_1|task_condition --
implying that the other individual conditions are estimated to be drawn
from the group distribution (but again this is not recommended unless you
would have many conditions).

You would also see it before sampling if you just look at your model
specification, eg. after defining your model if you just type
model_reg_v_angle_hier

if you specified v ~ 1 + (1|taskcondition) it should show you priors that
include v_1|taskcondition ~ Normal(mu,sigma)

(where mu and sigma would be priors that you specified or default). This
shows that the task condition v's would be estimated to come from a
normal distribution whose parameters are estimated (ie hierarchical).

**Comment by SaschaFroelich** [comment]
Thank you Michael.
