### ISSUE TITLE
NotImplementedError: Cannot convert models with non-default initial_values (PyMC)

### ISSUE THREAD

**Issue by krishnbera** [lnccbrown/HSSM#532]
**Describe the bug**
The sampling step fails once the sampling process is complete. 

**HSSM version**
0.2.3

**To Reproduce**
In the main tutorial, for the simple ddm model (analytical), set `sampler="mcmc"`. 
```
infer_data_simple_ddm_model = simple_ddm_model.sample(
    sampler="mcmc",  # type of sampler to choose, 'nuts_numpyro', 'nuts_blackjax' of default pymc nuts sampler
    cores=1,  # how many cores to use
    chains=2,  # how many chains to run
    draws=500,  # number of draws from the markov chain
    tune=500,  # number of burn-in samples
    idata_kwargs=dict(log_likelihood=True),  # return log likelihood
)  # mp_ctx="forkserver")
```

**Additional context**
The same error is encountered on black-box likelihoods when working with the Slice sampler and custom initial values. The error is resolved in this case by renaming all parameters so that any parameter name no longer resembles the typical parameter name (such as 'a', 'z', etc.).

**Comment by AlexanderFengler** [comment]
@krishnbera we made a big push this weekend to fix up the refactor to allow newest `pymc` / `bambi`. 

Will try to reproduce and fix this issue next.
