### ISSUE TITLE
Model does not consider initial values?

### ISSUE THREAD

**Issue by SaschaFroelich** [lnccbrown/HSSM#533]
I define initial values in my model, like so for example:

```
model_reg_v_angle_hier = hssm.HSSM(
    data = ddmdata,
    model = "angle",
    hierarchical = True,
    a = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=0.8),
    t = bmb.Prior("Uniform", lower=0., upper=2.0, initval=0.05),
)
```

If I understand correctly, the model should start sampling at those values, right? However, when I sample with 0 tune samples, the first values in the chain for `a` are always 1.5, and vor `t` 0.025, no matter what initial values I set. I know under some circumstances, the provided initial values can be used for a proposal distribution, but are not used as first sample in the MCMC chain. However, no matter what I set as initial values (even `a=20`), the first values of the chain for a parameter are always the same (as said, 1.5 for `a`, and 0.025 for `t`, for example).

Is it supposed to work like  that?

Thanks,
Sascha

I'm using HSSM 0.2.1

**Comment by frankmj** [comment]
Instead of specifying priors like that, try using the include statement and
then priors within that, like

include=[
{
"name": "a",
"formula": "a ~ 1 (1|participant_id)",
"prior": {
"Intercept": {"name": "Normal", "mu": 1, "sigma": 2, "initval": 1.0},
}

Then to check which values the model will sample at you cand run

model_reg_v_angle_hier.initial_point()

Michael

**Comment by SaschaFroelich** [comment]
Thank you Michael.

When I try to execute `model_reg_v_angle_hier.initial_point()`, I get the error `AttributeError: 'HSSM' object has no attribute 'initial_point'`. What works however is `model_reg_v_angle_hier.pymc_model.initial_point()`

So I specify the following model:

```
ddmdata = DDMutils.get_DDM_data2(2)
model_reg_v_angle_hier = hssm.HSSM(
    data = ddmdata,
    model = "angle",
    hierarchical = False,
    # a = bmb.Prior("Uniform", lower=0.1, upper=2.0, initval=0.8),
    t = bmb.Prior("Uniform", lower=0., upper=2.0, initval=0.05),
    include=[
        {
            "name": "a",
            "formula": "a ~ 1 + (1|participant_id)",
            "prior": {"Intercept": {"name": "Normal", "mu": 1, "sigma": 2, "initval": 1.0}},
        },
    ],
)
```

Then I execute `model_reg_v_angle_hier.pymc_model.initial_point()` and the output looks like this:

```
{'theta_interval__': array(0., dtype=float32),
 't_interval__': array(-4.4102697, dtype=float32),
 'z_interval__': array(1.1920929e-07, dtype=float32),
 'v_interval__': array(0., dtype=float32),
 'a_Intercept': array(1.5, dtype=float32),
 'a_1|participant_id_sigma_log__': array(0.91629076, dtype=float32),
 'a_1|participant_id_offset': array([-9.1435527e-03, -8.6042436e-04,  4.9897111e-03, -4.1726767e-04,
        -7.6002805e-03, -5.0465553e-03,  4.7089248e-03, -1.7132438e-03,
        -9.8426053e-03, -4.7590872e-03, -1.9940641e-03, -4.4571040e-03,
        -5.6314562e-03, -6.6744378e-03, -2.1954200e-03,  1.4191134e-03,
        -6.5092612e-03,  8.3025424e-03,  6.2621781e-03,  9.3745114e-03,
        -6.4498447e-03,  4.8032799e-03,  5.4137274e-03,  8.6939605e-03,
        -9.1963131e-03,  9.1390759e-03, -3.1517437e-03, -2.6973342e-03,
         5.7175937e-03, -5.6475294e-03, -4.5536724e-03,  2.9694757e-03,
        -9.5759181e-04, -3.0720248e-03, -4.8263567e-03,  6.1274450e-03,
        -7.1473378e-03, -6.8990011e-03,  9.1692507e-03, -7.9699681e-04,
         9.6667456e-03,  4.1215112e-03,  5.3927070e-03,  4.0297857e-03,
        -6.3806446e-03, -8.9251194e-03,  7.2894040e-03,  2.6426823e-03,
         6.0679242e-03,  6.8582785e-03,  4.4684107e-03,  2.9456110e-03,
        -4.4364491e-03,  7.1530143e-05, -5.7056765e-03, -5.6416518e-03,
         1.4724196e-03, -7.1452674e-03, -4.2335601e-03,  4.7991467e-03],
       dtype=float32)}
```

So where is the set initval of 1 relevant? `a_Intercept` is 1.5, and the values for the participants in `a_1|participant_id_offset` are all very clos to 0. For example, when I change `"Intercept": {"name": "Normal", "mu": 1, "sigma": 2, "initval": 1.0},` to `"Intercept": {"name": "Normal", "mu": 10, "sigma": 2, "initval": 10.0}`, the initial values of `model_reg_v_angle_hier.pymc_model.initial_point()` don't seem to be affected.


Best,
Sascha

**Comment by frankmj** [comment]
Hm, which hssm version are you using? initial_point should be something you
can call directly from the hssm model (which works for me). maybe @Paul Xu
***@***.***>  can comment on why this is not working for you.

also in my checks it does carry forth the initvals -- with the exception of
categorical variables (for which float64 is needed for them to get passed
to the model object but then still doesnt get incorporated in initial_point
- i made a note on that in our internal hssm channel, I think this might be
a real issue).

**Comment by AlexanderFengler** [comment]
hi @SaschaFroelich, 
the `hssm` class gained the `initial_point()` (slightly adjusted version of the one you are using through the attached `pymc_model`) only after `0.2.1`.

I recommend upgrading to the newest version (and in fact we will come out with the next version to accommodate the most recent upgrades to `pymc` and `bambi` very soon).

**Comment by SaschaFroelich** [comment]
Thank you everyone!
