### ISSUE TITLE
Try the Stan implementation of the DDM analytical likelihood

### ISSUE THREAD

**Issue by digicosmos86** [lnccbrown/HSSM#578]
https://github.com/stan-dev/math/blob/9b1f08be7e76c6468fc2fcf2f75d641a619ae349/stan/math/prim/prob/wiener_lpdf.hpp#L211

**Comment by AlexanderFengler** [comment]
after quick skim it looks like it's just the same algo...
possibly we can still harvest this for some numerical tricks

**Comment by cpaniaguam** [comment]
- [ ] control values of rt for log evaluations in `k_small` and `k_large`.
- [ ] clamp to respective upper bound if rt's are over
