### ISSUE TITLE
Suppress annomalous output in pytensor.function  

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#594]
Currently calls to `pytensor.function` in the `tests/test_likelihoods.py::test_analytical_gradient` test function report a "bug" that doesn't throw any exceptions and do not prevent the test from passing. The message comes from the `pytensor.function function` (see bug report https://github.com/pymc-devs/pytensor/issues/1037).

I suggest suppressing this kind of output from the `pytensor.fucntion` function, at least temporarily while the pymc devs resolve this problem. Something like the following seems to work:
```python
import contextlib
import logging
import os

class SuppressOutput:
    def __enter__(self):
        self._null_file = open(os.devnull, "w")
        self._stdout_context = contextlib.redirect_stdout(self._null_file)
        self._stderr_context = contextlib.redirect_stderr(self._null_file)
        self._stdout_context.__enter__()
        self._stderr_context.__enter__()
        logging.disable(logging.CRITICAL)  # Disable logging

    def __exit__(self, exc_type, exc_value, traceback):
        self._stdout_context.__exit__(exc_type, exc_value, traceback)
        self._stderr_context.__exit__(exc_type, exc_value, traceback)
        self._null_file.close()
        logging.disable(logging.NOTSET)  # Re-enable logging

# Example Usage
with SuppressOutput():
    buggy_function()

**Comment by digicosmos86** [comment]
PR merged
