### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#596]

**Comment by AlexanderFengler** [comment]
@cpaniaguam is this still blocked on some level?

**Comment by cpaniaguam** [comment]
I don't think so. Will try to set it up tomorrow.

**Comment by cpaniaguam** [comment]
@AlexanderFengler @digicosmos86 Sorry but I can't still configure the repo for codecov. A secret needs to be configured and only admins can do that. See https://docs.codecov.com/docs/quick-start#step-2-get-the-repository-upload-token
