### ISSUE TITLE
docs: improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#609]
1. Add clarification, remove ambiguity

https://github.com/lnccbrown/HSSM/blob/581c0fdbe4b0cdc646c79572371a7a6a3cb965fa/docs/CONTRIBUTING.md?plain=1#L7-L9

It's not clear to me where/when these labels are to be used. Should an issue be created first and add the suggested label? Or should the labeling be used in a PR? 

It feels like this block should be under the *Opening Issues* section. That would clarify where the labeling should be used.

2. Add definitions/descriptions

https://github.com/lnccbrown/HSSM/blob/581c0fdbe4b0cdc646c79572371a7a6a3cb965fa/docs/CONTRIBUTING.md?plain=1#L19

I think expanding the meaning of _fork_, _clone_, _feature branch_ would be beneficial. Maybe adding short definitions/descriptions would be useful for new contributors reading this guide.

3. Remove SSH commands
https://github.com/lnccbrown/HSSM/blob/581c0fdbe4b0cdc646c79572371a7a6a3cb965fa/docs/CONTRIBUTING.md?plain=1#L27-L31
https://github.com/lnccbrown/HSSM/blob/581c0fdbe4b0cdc646c79572371a7a6a3cb965fa/docs/CONTRIBUTING.md?plain=1#L41-L46

I think that if people are using ssh, they are very likely to understand this workflow already. I'd remove these commands to make the document simpler.

4. Inform of best practices early
https://github.com/lnccbrown/HSSM/blob/581c0fdbe4b0cdc646c79572371a7a6a3cb965fa/docs/CONTRIBUTING.md?plain=1#L62

Suggestion
> [!WARNING] 
> Routinely making changes in the main branch of a repository should be avoided. Always create a new _feature_ branch before making any changes and make your changes in the feature branch. 

5. Remove listing about poetry installing

It's not clear to me why this is required/advantageous. Can't users add their changes locally and test them without poetry? I think this section would need to be expanded (in a separate _advanced_ subsection?) if new dependencies are needed and how to use poetry to manage that.

Thoughts? @digicosmos86 @AlexanderFengler

**Comment by AlexanderFengler** [comment]
Re 1: 
These are probably meant more as high level concepts that specific contribution guidelines at that point. It's an option to expand it into concrete guidelines for labeling PRs not against it.

Re 2:
Agree that we should probably add short definitions on this (possibly some links)

Re 3: 
Agree

Re 4: 
Agree

Re 5:
Also agree that it's probably best to not make it seem that poetry is a must. 

Thanks @cpaniaguam.
